# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :haproxyVm do |haproxyVm|
    haproxyVm.vm.box = "bento/ubuntu-20.04"
    haproxyVm.vm.network :private_network, ip: "192.168.100.4"
    haproxyVm.vm.provision "shell", path: "ConfigHaproxy/script.sh"
    haproxyVm.vm.hostname = "haproxyVm"
  end

  config.vm.define :web1 do |web1|
    web1.vm.box = "bento/ubuntu-20.04"
    web1.vm.network :private_network, ip: "192.168.100.5"
    web1.vm.provision "shell", path: "ConfigWeb1/script.sh"
    web1.vm.hostname = "web1"
  end

  config.vm.define :web2 do |web2|
   web2.vm.box = "bento/ubuntu-20.04"
   web2.vm.network :private_network, ip: "192.168.100.6"
   web2.vm.provision "shell", path: "ConfigWeb2/script.sh"
   web2.vm.hostname = "web2"
  end
end 